name: Build CSS Bundle

on:
  push:
    branches:
      - main

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
      # - uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: latest

      - name: Install dependencies
        run: npm install

      - name: Bundle
        run: npm run build
      - uses: actions/upload-artifact@v4 # upload the bundle
        with:
          name: cacsscade.min.css
          path: ./cacsscade.min.css
          overwrite: true
          compression-level: 9

      - name: Push changes
        run: |
          git config --global user.name "GH workflow"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add cacsscade.min.css; git commit -m "build {{ github.sha }} bundle"
          git push
